version: 2
updates:
  - package-ecosystem: "gitsubmodule" # See documentation for possible values
    directory: "/themes/blowfish" # Location of package manifests
    schedule:
      interval: "weekly"